# 東京
tokyo = Station.create(name: "東京")
tokyo_1 = tokyo.children.create(name: "千代田区")
tokyo_1.children.create([{name: "東京駅"},{name: "秋葉原駅"},{name: "有楽町駅"},{name: "飯田橋駅"},{name: "神田駅"},{name: "大手町駅"},{name: "赤坂見附駅"},{name: "神保町駅"},{name: "水道橋駅"},{name: "市ヶ谷駅"},{name: "四ツ谷駅"},{name: "九段下駅"},{name: "霞ヶ関駅"},{name: "日比谷駅"},{name: "半蔵門駅"},{name: "二重橋前駅"},{name: "永田町駅"},{name: "麹町駅"},{name: "新御茶ノ水駅"},{name: "内幸町駅"},{name: "小川町駅"},{name: "岩本町駅"},{name: "末広駅"},{name: "竹橋駅"},{name: "淡路町駅"},{name: "国会議事堂前駅"},{name: "桜田門駅"}])
tokyo_2 = tokyo.children.create(name: "中央区")
tokyo_2.children.create([{name: "三越前駅"},{name: "銀座駅"},{name: "日本橋駅"},{name: "東銀座駅"},{name: "茅場町駅"},{name: "人形町駅"},{name: "築地駅"},{name: "勝どき駅"},{name: "八丁堀駅"},{name: "月島駅"},{name: "水天宮前駅"},{name: "京橋駅"},{name: "銀座一丁目駅"},{name: "新富町駅"},{name: "小伝馬町駅"},{name: "築地市場駅"},{name: "馬喰町駅"},{name: "宝島駅"},{name: "新日本橋駅"},{name: "馬喰横山駅"},{name: "東日本橋駅"},{name: "浜町駅"}])
tokyo_3 = tokyo.children.create(name: "港区")
tokyo_3.children.create([{name: "品川駅"},{name: "表参道駅"},{name: "新橋駅"},{name: "六本木駅"},{name: "浜松町駅"},{name: "田町駅"},{name: "麻布十番駅"},{name: "外苑前駅"},{name: "青山一丁目駅"},{name: "溜池山王駅"},{name: "神谷町駅"},{name: "赤坂駅"},{name: "虎ノ門駅"},{name: "大門駅"},{name: "六本木一丁目駅"},{name: "お台場海浜公園駅"},{name: "広尾駅"},{name: "汐留駅"},{name: "芝公園駅"},{name: "台場駅"},{name: "三田駅"},{name: "白金高輪駅"},{name: "乃木坂駅"},{name: "赤羽橋駅"},{name: "御成門駅"},{name: "泉岳寺駅"},{name: "白金台駅"},{name: "高輪台駅"},{name: "竹芝駅"},{name: "芝浦ふ頭駅"},{name: "日の出駅"},{name: "高輪ゲートウェイ駅"}])
tokyo_4 = tokyo.children.create(name: "新宿区")
tokyo_4.children.create([{name: "新宿駅"},{name: "新宿三丁目駅"},{name: "東新宿駅"},{name: "高田馬場駅"},{name: "新大久保駅"},{name: "神楽坂駅"},{name: "信濃町駅"},{name: "西新宿駅"},{name: "新宿御苑前駅"},{name: "四谷三丁目駅"},{name: "早稲田駅"},{name: "大久保駅"},{name: "曙橋駅"},{name: "西早稲田駅"},{name: "若松河田駅"},{name: "中井駅"},{name: "西武新宿駅"},{name: "都庁前駅"},{name: "西影橋駅"},{name: "新宿西口駅"},{name: "国立競技場駅"},{name: "落合南長崎駅"},{name: "落合駅"},{name: "牛込神楽坂駅"},{name: "牛込柳町駅"},{name: "下落合駅"},{name: "西新宿五丁目駅"}])
tokyo_5 = tokyo.children.create(name: "文京区")
tokyo_5.children.create([{name: "御茶ノ水駅"},{name: "後楽園駅"},{name: "護国寺駅"},{name: "江戸川駅"},{name: "本郷三丁目駅"},{name: "茗荷谷駅"},{name: "湯島駅"},{name: "春日駅"},{name: "白山駅"},{name: "千駄木駅"},{name: "根津駅"},{name: "東大前駅"},{name: "千石駅"},{name: "本駒込駅"}])
tokyo_6 = tokyo.children.create(name: "台東区")
tokyo_6.children.create([{name: "上野駅"},{name: "浅草駅"},{name: "御徒町駅"},{name: "浅草橋駅"},{name: "鶯谷駅"},{name: "三ノ輪駅"},{name: "蔵前駅"},{name: "入谷駅"},{name: "田原町駅"},{name: "京成上野駅"},{name: "新御徒町駅"},{name: "上野広小路駅"},{name: "仲卸徒町駅"},{name: "稲荷駅"},{name: "上野徒町駅"}])
tokyo_7 = tokyo.children.create(name: "墨田区")
tokyo_7.children.create([{name: "両国駅"},{name: "錦糸町駅"},{name: "押上駅"},{name: "とうきょうスカイツリー駅"},{name: "両国駅"},{name: "曳舟駅"},{name: "菊川駅"},{name: "本所吾妻橋駅"},{name: "東向島駅"},{name: "八広駅"},{name: "京成曳舟駅"},{name: "鐘ヶ淵駅"},{name: "小村井駅"},{name: "東あずま駅"}])
tokyo_8 = tokyo.children.create(name: "江東区")
tokyo_8.children.create([{name: "豊洲駅"},{name: "亀戸駅"},{name: "門前仲町駅"},{name: "東陽町駅"},{name: "神田駅"},{name: "新木場駅"},{name: "木場駅"},{name: "清澄白河駅"},{name: "南砂町駅"},{name: "東京テレポート駅"},{name: "国際展示場駅"},{name: "住吉駅"},{name: "森下駅"},{name: "大島駅"},{name: "潮見駅"},{name: "西大島駅"},{name: "東大島駅"},{name: "有明テニスの森駅"},{name: "新豊洲駅"},{name: "東京国際クルーズターミナル駅"},{name: "テレコムセンター駅"},{name: "東雲駅"},{name: "辰巳駅"},{name: "有明駅"},{name: "市場前駅"},{name: "越中島駅"},{name: "青海駅"},{name: "東京ビッグサイト駅"},{name: "亀戸水神駅"}])
tokyo_9 = tokyo.children.create(name: "品川区")
tokyo_9.children.create([{name: "五反田駅"},{name: "目黒駅"},{name: "大井町駅"},{name: "大崎駅"},{name: "武蔵小山駅"},{name: "品川シーサイド駅"},{name: "天王洲アイル駅"},{name: "不動前駅"},{name: "青物横丁駅"},{name: "旗の台駅"},{name: "西大井駅"},{name: "戸越銀座駅"},{name: "大森海岸駅"},{name: "中延駅"},{name: "鮫洲駅"},{name: "西小山駅"},{name: "新馬場駅"},{name: "戸越駅"},{name: "立会川駅"},{name: "北品川駅"},{name: "荏原町駅"},{name: "戸越公園駅"},{name: "大井競馬場前駅"},{name: "荏原中延駅"},{name: "大崎広小路駅"},{name: "下神明駅"}])
tokyo_10 = tokyo.children.create(name: "目黒区")
tokyo_10.children.create([{name: "中目黒駅"},{name: "自由が丘駅"},{name: "学芸大学駅"},{name: "都立大学駅"},{name: "祐天寺駅"},{name: "品駒場東大前駅"},{name: "洗足駅"},{name: "緑が丘駅"}])
tokyo_11 = tokyo.children.create(name: "大田区")
tokyo_11.children.create([{name: "羽田空港第1・第2ターミナル駅"},{name: "蒲田駅"},{name: "大森駅"},{name: "京急蒲田駅"},{name: "羽田空港第2ターミナル駅"},{name: "平和島駅"},{name: "大岡山駅"},{name: "羽田空港第3ターミナル駅"},{name: "羽田空港第1ターミナル駅"},{name: "田園調布駅"},{name: "池上駅"},{name: "西馬込駅"},{name: "流通センター駅"},{name: "大鳥居駅"},{name: "多摩川駅"},{name: "雑色駅"},{name: "馬込駅"},{name: "糀谷駅"},{name: "下丸子駅"},{name: "大森町駅"},{name: "穴守稲荷駅"},{name: "梅屋敷駅"},{name: "雪が谷大塚駅"},{name: "矢口渡駅"},{name: "武蔵新田駅"},{name: "天空橋駅"},{name: "長原駅"},{name: "六郷土手駅"},{name: "御嶽山駅"},{name: "鵜の木駅"},{name: "久が原駅"},{name: "千鳥町駅"},{name: "石川台駅"},{name: "新整備場駅"},{name: "蓮沼駅"},{name: "沼部駅"},{name: "昭和島駅"},{name: "北千束駅"},{name: "羽田空港第3ターミナル駅"},{name: "整備場駅"},{name: "洗足池駅"}])
tokyo_12 = tokyo.children.create(name: "世田谷区")
tokyo_12.children.create([{name: "下北沢駅"},{name: "二子玉川駅"},{name: "三軒茶屋駅"},{name: "成城学園前駅"},{name: "経堂駅"},{name: "池尻大橋駅"},{name: "千歳烏山駅"},{name: "用賀駅"},{name: "駒沢大学駅"},{name: "明大前駅"},{name: "千歳船橋駅"},{name: "桜新町駅"},{name: "祖師ヶ谷大蔵駅"},{name: "等々力駅"},{name: "下高井戸駅"},{name: "喜多見駅"},{name: "芦花公園駅"},{name: "桜上水駅"},{name: "梅ヶ丘駅"},{name: "尾山台駅"},{name: "豪徳寺駅"},{name: "上野毛駅"},{name: "代田橋駅"},{name: "世田谷駅"},{name: "奥沢駅"},{name: "上北沢駅"},{name: "松陰神社駅"},{name: "新代田駅"},{name: "上町駅"},{name: "東松原駅"},{name: "九品仏駅"},{name: "世田谷代田駅"},{name: "池ノ上駅"},{name: "若林駅"},{name: "東北沢駅"},{name: "宮の坂駅"},{name: "松原駅"},{name: "山下駅"},{name: "西太子堂駅"}])
tokyo_13 = tokyo.children.create(name: "渋谷区")
tokyo_13.children.create([{name: "渋谷駅"},{name: "代々木駅"},{name: "原宿駅"},{name: "代々木公園駅"},{name: "恵比寿駅"},{name: "代官山駅"},{name: "代々木上原駅"},{name: "初台駅"},{name: "笹塚駅"},{name: "千駄ヶ谷駅"},{name: "明治神宮前駅"},{name: "幡々谷駅"},{name: "神泉駅"},{name: "参宮橋駅"},{name: "南新宿駅"},{name: "代々木八幡駅"},{name: "北参道駅"}])
tokyo_14 = tokyo.children.create(name: "中野区")
tokyo_14.children.create([{name: "中野駅"},{name: "東中野駅"},{name: "中野坂上駅"},{name: "野方駅"},{name: "新中野駅"},{name: "鷺ノ宮駅"},{name: "沼袋駅"},{name: "新江古田駅"},{name: "新井薬師前駅"},{name: "中野新橋駅"},{name: "中野富士見町駅"},{name: "都立家政駅"}])
tokyo_15 = tokyo.children.create(name: "杉並区")
tokyo_15.children.create([{name: "荻窪駅"},{name: "高円寺駅"},{name: "阿佐ケ谷駅"},{name: "西荻窪駅"},{name: "永福町駅"},{name: "高井戸駅"},{name: "久我山駅"},{name: "方南町駅"},{name: "八幡山駅"},{name: "南阿佐ケ谷駅"},{name: "東高円寺駅"},{name: "新高円寺駅"},{name: "浜田山駅"},{name: "井荻駅"},{name: "下井草駅"},{name: "上井草駅"},{name: "西永福駅"},{name: "富士見ヶ丘駅"}])
tokyo_16 = tokyo.children.create(name: "豊島区")
tokyo_16.children.create([{name: "池袋駅"},{name: "大塚駅"},{name: "巣鴨駅"},{name: "駒込駅"},{name: "目白駅"},{name: "板橋駅"},{name: "東池袋駅"},{name: "要町駅"},{name: "千川駅"},{name: "西巣鴨駅"},{name: "新大塚駅"},{name: "椎名町駅"},{name: "雑司が谷駅"},{name: "東長崎駅"},{name: "下板橋駅"},{name: "新庚申塚駅"},{name: "大塚駅前駅"},{name: "北池袋駅"},{name: "庚申塚駅"},{name: "学習院下駅"},{name: "鬼子母神前駅"},{name: "向原駅"},{name: "都電雑司々谷駅"},{name: "巣鴨新田駅"},{name: "東池袋四丁目駅"}])
tokyo_17 = tokyo.children.create(name: "北区")
tokyo_17.children.create([{name: "王子駅"},{name: "赤羽駅"},{name: "十条駅"},{name: "田端駅"},{name: "栄町駅"},{name: "東十条駅"},{name: "浮間舟渡駅"},{name: "王子神谷駅"},{name: "北赤羽駅"},{name: "尾久駅"},{name: "赤羽岩淵駅"},{name: "志茂駅"},{name: "上中里駅"},{name: "西ヶ原駅"},{name: "梶原駅"},{name: "王子駅前駅"},{name: "西ヶ原四丁目駅"},{name: "滝野川一丁目駅"},{name: "飛鳥山駅"}])
tokyo_18 = tokyo.children.create(name: "荒川区")
tokyo_18.children.create([{name: "日暮里駅"},{name: "西日暮里駅"},{name: "町屋駅前駅"},{name: "町屋駅"},{name: "南千住駅"},{name: "三河島駅"},{name: "熊野前駅"},{name: "新三河島駅"},{name: "赤土小学校前駅"},{name: "三ノ輪橋駅"},{name: "小台駅"},{name: "宮ノ前駅"},{name: "荒川区役所前駅"},{name: "新川車庫前駅"},{name: "荒川遊園地前駅"},{name: "荒川七丁目駅"},{name: "荒川二丁目駅"},{name: "町屋二丁目駅"},{name: "東尾久三丁目駅"},{name: "荒川一中前駅"}])
tokyo_19 = tokyo.children.create(name: "板橋区")
tokyo_19.children.create([{name: "成増駅"},{name: "高島平駅"},{name: "地下鉄成増駅"},{name: "東武練馬駅"},{name: "大山駅"},{name: "ときわ台駅"},{name: "北板橋駅"},{name: "板橋区役所前駅"},{name: "志村三丁目駅"},{name: "志村坂上駅"},{name: "板橋本町駅"},{name: "西台駅"},{name: "中板橋駅"},{name: "本蓮沼駅"},{name: "新板橋駅"},{name: "下赤塚駅"},{name: "蓮根駅"},{name: "西高島平駅"},{name: "新高島平駅"}])
tokyo_20 = tokyo.children.create(name: "練馬区")
tokyo_20.children.create([{name: "練馬駅"},{name: "大泉学園駅"},{name: "石神井公園駅"},{name: "光が丘駅"},{name: "江古田駅"},{name: "武蔵関駅"},{name: "練馬高野台駅"},{name: "地下鉄赤塚駅"},{name: "豊島園駅"},{name: "小竹向原駅"},{name: "神石神井駅"},{name: "平和台駅"},{name: "中村橋駅"},{name: "氷川台駅"},{name: "富士見台駅"},{name: "練馬春日町駅"},{name: "桜台駅"},{name: "新桜台駅"},{name: "豊島園駅"}])
tokyo_21 = tokyo.children.create(name: "足立区")
tokyo_21.children.create([{name: "北千住駅"},{name: "綾瀬駅"},{name: "西新井駅"},{name: "竹ノ塚駅"},{name: "梅島駅"},{name: "北綾瀬駅"},{name: "五反野駅"},{name: "六町駅"},{name: "千住大橋駅"},{name: "見沼代親水公園駅"},{name: "新井大師西駅"},{name: "江北駅"},{name: "青井駅"},{name: "京成関屋駅"},{name: "大師前駅"},{name: "舎人公園駅"},{name: "牛田駅"},{name: "谷在家駅"},{name: "舎人駅"},{name: "小菅駅"},{name: "堀切駅"},{name: "足立小台駅"},{name: "高野駅"},{name: "扇大橋駅"}])
tokyo_22 = tokyo.children.create(name: "葛飾区")
tokyo_22.children.create([{name: "新小岩駅"},{name: "亀有駅"},{name: "金町駅"},{name: "京成高砂駅"},{name: "堀切菖蒲園駅"},{name: "柴又駅"},{name: "青砥駅"},{name: "京成立石駅"},{name: "お花茶屋駅"},{name: "四ツ木園駅"},{name: "京成金町駅"},{name: "新柴又駅"}])
tokyo_23 = tokyo.children.create(name: "江戸川区")
tokyo_23.children.create([{name: "葛西臨海公園駅"},{name: "葛西駅"},{name: "小岩駅"},{name: "西葛西駅"},{name: "船堀駅"},{name: "瑞江駅"},{name: "平井駅"},{name: "一之江駅"},{name: "篠崎駅"},{name: "京成小岩駅"},{name: "江戸川駅"}])

# 埼玉
saitama = Station.create(name: "埼玉")
saitama_1 = saitama.children.create(name: "さいたま市西区")
saitama_1.children.create([{name: "西大宮駅"},{name: "指扇駅"}])
saitama_2 = saitama.children.create(name: "さいたま市西区")
saitama_2.children.create([{name: "宮原駅"},{name: "日進駅"},{name: "土呂駅"},{name: "加茂宮駅"},{name: "吉野原駅"},{name: "今羽駅"},{name: "東宮原駅"}])
saitama_3 = saitama.children.create(name: "さいたま市大宮区")
saitama_3.children.create([{name: "大宮駅"},{name: "さいたま新都心駅"},{name: "大宮公園駅"},{name: "鉄道博物館駅"},{name: "北大宮駅"}])
saitama_4 = saitama.children.create(name: "さいたま市見沼区")
saitama_4.children.create([{name: "東大宮駅"},{name: "七里駅"},{name: "大和田駅"}])
saitama_5 = saitama.children.create(name: "さいたま市中央区")
saitama_5.children.create([{name: "南与野駅"},{name: "北与野駅"},{name: "与野本町駅"}])
saitama_6 = saitama.children.create(name: "さいたま市桜区")
saitama_6.children.create([{name: "西浦和駅"}])
saitama_7 = saitama.children.create(name: "さいたま市浦和区")
saitama_7.children.create([{name: "浦和駅"},{name: "北浦和駅"},{name: "与野駅"}])
saitama_8 = saitama.children.create(name: "さいたま市南区")
saitama_8.children.create([{name: "武蔵浦和駅"},{name: "南浦和駅"},{name: "中浦和駅"}])
saitama_9 = saitama.children.create(name: "さいたま市緑区")
saitama_9.children.create([{name: "東浦和駅"},{name: "浦和美園駅"}])
saitama_10 = saitama.children.create(name: "さいたま市岩槻区")
saitama_10.children.create([{name: "岩槻駅"},{name: "東岩槻駅"}])
# 千葉
chiba = Station.create(name: "千葉")
chiba_1 = chiba.children.create(name: "千葉市中央区")
chiba_1.children.create([{name: "千葉駅"},{name: "蘇我駅"},{name: "千葉みなと駅"},{name: "西千葉駅"},{name: "栄町駅"},{name: "県庁前駅"},{name: "市役所前駅"},{name: "西登戸駅"},{name: "千葉中央駅"},{name: "本千葉駅"},{name: "京成千葉駅"},{name: "浜野駅"},{name: "東千葉駅"},{name: "千葉寺駅"},{name: "大森台駅"},{name: "新千葉駅"},{name: "千葉公園駅"},{name: "葭川公園駅"}])
chiba_2 = chiba.children.create(name: "千葉市花見川区")
chiba_2.children.create([{name: "幕張本郷駅"},{name: "新検見川駅"},{name: "幕張駅"},{name: "京成幕張駅"},{name: "京成幕張本郷駅"},{name: "検見川駅"}])
chiba_3 = chiba.children.create(name: "千葉市稲毛区")
chiba_3.children.create([{name: "稲毛駅"},{name: "スポーツセンター駅"},{name: "作草部駅"},{name: "天台駅"},{name: "京成稲毛駅"},{name: "みどり台駅"},{name: "穴川駅"}])
chiba_4 = chiba.children.create(name: "千葉市若葉区")
chiba_4.children.create([{name: "都賀駅"},{name: "動物公園駅"},{name: "千城台駅"},{name: "千城台北駅"},{name: "桜木駅"},{name: "みつわ台駅"},{name: "小倉台駅"}])
chiba_5 = chiba.children.create(name: "千葉市緑区")
chiba_5.children.create([{name: "鎌取駅"},{name: "土気駅"},{name: "誉田駅"},{name: "おゆみ野駅"},{name: "学園前駅"}])
chiba_6 = chiba.children.create(name: "千葉市美浜区")
chiba_6.children.create([{name: "海浜幕張駅"},{name: "稲毛海岸駅"},{name: "検見川浜駅"}])

# 神奈川
kanagawa = Station.create(name: "神奈川")
kanagawa_1 = kanagawa.children.create(name: "横浜市鶴見区")
kanagawa_1.children.create([{name: "鶴見駅"},{name: "弁天橋駅"},{name: "海芝浦駅"},{name: "新芝浦駅"},{name: "京急鶴見駅"},{name: "生麦駅"},{name: "矢向駅"},{name: "鶴見市場駅"},{name: "鶴見小野駅"},{name: "安善駅"},{name: "浅野駅"},{name: "花月総持寺駅"},{name: "国道駅"}])
kanagawa_2 = kanagawa.children.create(name: "横浜市神奈川区")
kanagawa_2.children.create([{name: "東神奈川駅"},{name: "新子安駅"},{name: "白楽駅"},{name: "大口駅"},{name: "東白楽駅"},{name: "反町駅"},{name: "神奈川新町駅"},{name: "片倉町駅"},{name: "京急東神奈川駅"},{name: "子安駅"},{name: "神奈川駅"},{name: "三ッ沢上町駅"},{name: "三ッ沢下町駅"},{name: "京急新子安駅"},{name: "羽沢横浜国大駅"}])
kanagawa_3 = kanagawa.children.create(name: "横浜市西区")
kanagawa_3.children.create([{name: "横浜駅"},{name: "みなとみらい駅"},{name: "新高島駅"},{name: "戸部駅"},{name: "西横浜駅"},{name: "高島町駅"},{name: "平沼橋駅"}])
kanagawa_4 = kanagawa.children.create(name: "横浜市中区")
kanagawa_4.children.create([{name: "桜木町駅"},{name: "関内駅"},{name: "元町・中華街駅"},{name: "馬車道駅"},{name: "石川町駅"},{name: "日本大通り駅"},{name: "日ノ出町駅"},{name: "伊勢崎長者町駅"},{name: "山手駅"},{name: "阪東橋駅"}])
kanagawa_5 = kanagawa.children.create(name: "横浜市南区")
kanagawa_5.children.create([{name: "黄金町駅"},{name: "井土々谷駅"},{name: "弘明寺駅"},{name: "蒔田駅"},{name: "吉野町駅"},{name: "南太田駅"}])
kanagawa_6 = kanagawa.children.create(name: "横浜市保土ケ谷区")
kanagawa_6.children.create([{name: "保土々谷駅"},{name: "天王町駅"},{name: "星川駅"},{name: "西谷駅"},{name: "和田町駅"},{name: "上星川駅"}])
kanagawa_7 = kanagawa.children.create(name: "横浜市磯子区")
kanagawa_7.children.create([{name: "新杉田駅"},{name: "根岸駅"},{name: "磯子駅"},{name: "洋光台駅"},{name: "杉田駅"},{name: "屏風浦駅"}])
